// Lista de requisitos por nivel de CG.
// Columna 1 = "Condición 1", Columna 2 = "Condición 2" (puede venir vacía).
export const HQ_REQUIREMENTS = [
  { level: 2,  c1: "Terreno de Entrenamiento Nivel 1",             c2: "" },
  { level: 3,  c1: "Muralla Nivel 2",                              c2: "" },
  { level: 4,  c1: "Barracas Nivel 3",                             c2: "Terreno de Entrenamiento Nivel 3" },
  { level: 5,  c1: "Muralla Nivel 4",                              c2: "Barracas Nivel 4" },
  { level: 6,  c1: "Muralla Nivel 5",                              c2: "Terreno de Entrenamiento Nivel 5" },
  { level: 7,  c1: "Muralla Nivel 6",                              c2: "Centro de Tanques Nivel 6" },
  { level: 8,  c1: "Centro Tecnológico Nivel 7",                   c2: "Centro de Apoyo de Alianza Nivel 7" },
  { level: 9,  c1: "Centro Tecnológico Nivel 8",                   c2: "Centro de Tanques Nivel 8" },
  { level:10,  c1: "Centro Tecnológico Nivel 9",                   c2: "Hospital Nivel 9" },
  { level:11,  c1: "Centro Tecnológico Nivel 10",                  c2: "Muralla Nivel 10" },
  { level:12,  c1: "Centro Tecnológico Nivel 11",                  c2: "Barracas Nivel 11" },
  { level:13,  c1: "Centro Tecnológico Nivel 12",                  c2: "Centro de Tanques Nivel 12" },
  { level:14,  c1: "Centro Tecnológico Nivel 13",                  c2: "Terreno de Entrenamiento Nivel 13" },
  { level:15,  c1: "Centro Tecnológico Nivel 14",                  c2: "Muralla Nivel 14" },
  { level:16,  c1: "Centro Tecnológico Nivel 15",                  c2: "Centro de Apoyo de Alianza Nivel 15" },
  { level:17,  c1: "Centro Tecnológico Nivel 16",                  c2: "Centro de Tanques Nivel 16" },
  { level:18,  c1: "Centro Tecnológico Nivel 17",                  c2: "Hospital Nivel 17" },
  { level:19,  c1: "Centro Tecnológico Nivel 18",                  c2: "Muralla Nivel 18" },
  { level:20,  c1: "Centro Tecnológico Nivel 19",                  c2: "Barracas Nivel 19" },
  { level:21,  c1: "Centro Tecnológico Nivel 20",                  c2: "Centro de Tanques Nivel 20" },
  { level:22,  c1: "Centro Tecnológico Nivel 21",                  c2: "Terreno de Entrenamiento Nivel 21" },
  { level:23,  c1: "Centro Tecnológico Nivel 22",                  c2: "Muralla Nivel 22" },
  { level:24,  c1: "Centro Tecnológico Nivel 23",                  c2: "Centro de Apoyo de Alianza Nivel 23" },
  { level:25,  c1: "Centro Tecnológico Nivel 24",                  c2: "Centro de Tanques Nivel 24" },
  { level:26,  c1: "Centro Tecnológico Nivel 25",                  c2: "Hospital Nivel 25" },
  { level:27,  c1: "Centro Tecnológico Nivel 26",                  c2: "Muralla Nivel 26" },
  { level:28,  c1: "Centro Tecnológico Nivel 27",                  c2: "Barracas Nivel 27" },
  { level:29,  c1: "Centro Tecnológico Nivel 28",                  c2: "Centro de Tanques Nivel 28" },
  { level:30,  c1: "Centro Tecnológico Nivel 29",                  c2: "Terreno de Entrenamiento Nivel 29" },
];